### ISSUE TITLE
Expose `Serial_type` module type publicly to enable first-class module usage

### ISSUE THREAD

**Issue by eeelllccc** [m-laniakea/oserial#2]
Making the `Serial_type` public would enable the following first class module pattern:
```ocaml
let module Serial' = Serial.Make (struct
  let port = <dynamically injected port path>
  let baud_rate = 115200
end) in
let serial_mod = (module Serial' : Serial_intf.Serial_type) in
(* Consume the packed first-class module with a function. *)
some_function serial_mod
```
In this example the serial port can be determined at runtime (e.g. with command-line args).

PS thanks for the good work, useful project.

**Comment by m-laniakea** [comment]
Hi edchapman! 
Glad you find this useful, and thank you for opening this ticket.

The following code determines the port via command-line args:

```ocaml
(* {{{ setup *)
let usage_msg = "test -port <port>"
let arg_port = ref ""

let speclist = [("-port", Arg.Set_string arg_port, "Set serial port")]

let () =
    Arg.parse speclist (fun _ -> ()) usage_msg;
    if "" = !arg_port then Arg.usage speclist usage_msg else

    Printf.printf "Using port '%s'" !arg_port
(* }}} setup-end *)

    module S_Config = struct
        let port = !arg_port
        let baud_rate = 115200
    end

    module Serial_0 = Serial.Make(S_Config)
```

Would you please explain a bit more what you'd like to see and why that is so?

**Comment by eeelllccc** [comment]
Hi, thanks for the quick response. I should have been a bit more specific, but I had forgotten why I was trying to make a first-class module in the first place! (and I'm new to OCaml so I could be missing something too):

The entry point to my program is an `Lwt_main.run`, hence most of my own modules have functions that take and return promises. There are two options (i think!), neither of which are possible currently:

1. Construct the `Serial_0` module within my library code, which would be ideal because it should belong in my module for handling program outputs. But this isn't possible because `Serial.Make` encapsulates an `Lwt_main.run`, which ends up nested within the `Lwt_main.run` at my program entry point, and this nesting isn't allowed.

> [Note that you must not make nested calls to Lwt_main.run.](https://ocsigen.org/lwt/latest/manual/manual)

2. Construct the `Serial_0` right after CLI parsing (as above), and just before my program entry point. I would then need to pass around the `Serial_0` module as a [first-class module](https://ocaml.org/manual/5.2/firstclassmodules.html) in order to use it within my library code that needs to write to a serial interface. This is shown in the code when I opened the issue - where `some_function` would be my program entry point.

There is actually another reason to favour 1. over 2. (which is why in the end I took your code and factored out the `Lwt_main.run`), which is that you can `Serial.make` new serial connections during the program (from within a top level `Lwt_main.run`), e.g. if a device connects on a serial port after the program starts.

**Comment by m-laniakea** [comment]
What you're saying makes a lot of sense. 
Now it's clear where you're coming from, so thank you for these details.

You're right, the examples work because the module is created before the call to `Lwt_main.run`. 
Your use case of wanting to create the Serial module sometimes after the first call to Lwt_main is very reasonable.

No guarantees on a quick turnaround here, but I'm sure we can come up with something good.

**Comment by eeelllccc** [comment]
No worries, sounds good - I do have something that works in the meantime that basically removes the `Lwt_main.run` and uses promises at the api. Unfortunately didn't fork your repo and make edits, so a PR doesn't make sense. But if you were curious about what I did (think there probably are much nicer solutions out there) then it's [here](https://github.com/edchapman88/getting/blob/main/lib/serial.mli) on github.

**Comment by m-laniakea** [comment]
Your  `config -> t Lwt.t` is nice. 
~~`config -> (t, err) Lwt_result.t` would be even better, because `make` is not guaranteed to succeed.~~

**Comment by m-laniakea** [comment]
Looked at this. ~~and didn't find a module-based appoach that was really satisfying.~~
So now there's a struct-based approach, which you can view [here](https://github.com/m-laniakea/oserial/blob/a3fa69efd5b7befa0fce42e524f8cc58a245a138/examples/io.ml).

Usage example:
```ocaml
open Lwt.Infix

module S = Shared

let port = "/dev/pts/19"
let baud_rate = 115200

let () =
	Lwt_main.run begin
		Serial.connect ~port ~baud_rate >>= function
		| Ok connection ->
			Lwt_io.printl "Awaiting input. Enter 'quit' when done..." >>= fun () ->
			Serial.io_loop connection (Some "quit")
		| Error e -> S.print_exn_conn e
	end
```
Note that it plays nicely with pre-existing `Lwt_main.run`s now.

That connection can then be optionally used to make a module:
```ocaml
let module S0 = (val Serial.make connection) in
S0.write_line "Greetings!"
```

@edchapman88 Would love to hear your thoughts before merging.
